config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :products
  

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skurikhin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table border="1">
  <tr>
    <th>Products</th>
  </tr>
<% @products.each do |product| %>  
  <tr>  
    <td><%= product.name %></td>
  </tr>
<% end %>
</table>

app/views/welcome/index.html.erb
<h1>Hello World</h1>

<%=link_to "Products", products_url %>